# Generated by Django 6.0.2 on 2026-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
